name: Deploy

on:
  # 推送时执行
  push:
    branches: [dev]
  # 可手动执行
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy server
    runs-on: ubuntu-latest
    steps:
      # 1、检出源码
      - name: Checkout
        uses: actions/checkout@v7
      # 2、移除 POM 中的国内镜像仓库（CI 环境不稳定）
      - name: Remove repository mirrors
        run: |
          sed -i.bak '/<repositories>/,/<\/repositories>/d' pom.xml
          sed -i.bak '/<pluginRepositories>/,/<\/pluginRepositories>/d' pom.xml
      # 3、安装 Java 环境
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      # 4、打包
      - name: Build
        run: ./mvnw -B package
      # 5、拷贝到服务器
      - name: Copy
        uses: appleboy/scp-action@917f8b81dfc1ccd331fef9e2d61bdc6c8be94634 # v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ./continew-server/target/app/*
          target: ${{ secrets.SERVER_PATH }}/continew-admin
          strip_components: 3
      # 6、启动
      - name: Start
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            docker-compose up --force-recreate --build -d continew-server
            docker images | grep none | awk '{print $3}' | xargs -r docker rmi
